### ISSUE TITLE
Do you want to link this in the vdirsyncer docs?

### ISSUE THREAD

**Issue by untitaker** [DamienCassou/vdirel#1]
https://vdirsyncer.readthedocs.io/en/stable/supported.html#client-applications lists a few applications that work with vdirsyncer and are intended to be used by other people. Do you think vdirel should be on that list?

**Comment by DamienCassou** [comment]
yes, you can add it if you want. Thanks

**Comment by untitaker** [comment]
Done

**Comment by DamienCassou** [comment]
Thanks
