### ISSUE TITLE
Contacts list ?

### ISSUE THREAD

**Issue by bepolymathe** [DamienCassou/vdirel#17]
Hi, 

Thank you for this very useful package that I use with emacs+mu4e 

For the rest, I use khard that I synchronize with Nextcloud (and my phone).... 

Just one question. Is it possible to use all this with lists? I like to use lists for projects.

**Comment by DamienCassou** [comment]
What do you mean by list? Can you please describe your use case?

If you use khard, I suggest you try https://gitea.petton.fr/DamienCassou/khardel as well.

**Comment by gour** [comment]
> If you use khard, I suggest you try https://gitea.petton.fr/DamienCassou/khardel as well.

What about vdirsyncer's [issue](https://github.com/pimutils/vdirsyncer/issues/790), iow. what is the future of khard/khal **without** vdirsyncer?

**Comment by DamienCassou** [comment]
> What about vdirsyncer's issue, iow. what is the future of khard/khal without vdirsyncer?

I didn't know about this issue. For now I don't want to worry about that. Someone might take the project over or another project might emerge.

**Comment by bepolymathe** [comment]
Thanks for khardel !
