### ISSUE TITLE
Error in Helm buffer

### ISSUE THREAD

**Issue by dschrempf** [DamienCassou/vdirel#19]
Hi,

when executing `vdir-helm-select-email` and typing any combination of letters, I get the following error:

![2021-08-02_01-01-small](https://user-images.githubusercontent.com/5596239/127788033-8824950a-f4c5-430b-b579-b3ee4ea48c7e.png)

Only when one match remains, it is shown correctly.

(I do have a full backtrace, but it shows private data. It is quite hard to get a backtrace when using helm, so I took a screenshot). Please let me know if I can provide further details!

**Comment by DamienCassou** [comment]
Hi @dschrempf. Thank you for your bug report. I don't use helm nor vdirel anymore (do you know [khardel](https://github.com/DamienCassou/khardel)?).

Still, I have tried to reproduce and things work fine for me. I guess the contact you picked is in a non-supported format. Can you please try to reproduce with a fake contact and send me the details?

**Comment by dschrempf** [comment]
Thank you for your reply. I have changed to a `vdirsyncer`, `khard`, `khardel` stack :). Complicated but it seems to work now!u

**Comment by fuzunspm** [comment]
having the same issue, could you find a fix?
