### ISSUE TITLE
more than one vdir

### ISSUE THREAD

**Issue by gour** [DamienCassou/vdirel#2]
Hello,

just switched to Emacs and would like to have syncing of my calendars/contacts with my phone via Baikal server.

Before that was using vdirsyncer/khal/khard which worked nicely, but org-caldav-sync package eliminates need for using khal along with vdirsyncer.

However, there is no org-cardav-sync package which would do the same for contacts and it looks that vdirel might be the most elegant solution and better than regular import/export of *.vcf files to keep e.g. BBDB in sync.

Considering that I use(d) khard/vdirsyncer to sync _two_ different addresbooks (me & my wife) I wonder whether `vdirel` does support having more than one vdirel repository, iow. my tree looks as:

```
collection/
├── abook-1
│   ├── hash-1-1.vcf
│   ├── hash1-2.vcf
│   ├── ...

│   └── hash-1-n.vcf
└── abook-2
    ├── hash-2-1.vcf
    ├── hash-2-2.vcf
...
```

Any hint how to configure it?

**Comment by DamienCassou** [comment]
Hi Saša,

> would like to have syncing of my calendars/contacts with my phone via Baikal server

good idea :-). That's exactly what I do. If you are that kind of guy, may I also suggest password-store for your passwords? There are several packages to integrate password store with Emacs, Firefox and Android.

> Before that was using vdirsyncer/khal/khard which worked nicely, but org-caldav-sync package eliminates need for using khal along with vdirsyncer.

I'm using khard (to edit my contacts mostly) but not khal.

> I wonder whether vdirel does support having more than one vdirel repository

I wrote all of the code to be able to use multiple repositories but never did that (as I only have one). What use case do you have? Would you prefer that vdirel shows all contacts from both repositories as if they came from the same? Or would you prefer to choose which repository is currently active and make all commands use that? Or would you prefer that each command first asks you which repository to fetch contacts from?

**Comment by gour** [comment]
Hello Damien,

> good idea :-). That's exactly what I do. 

Before I was using ownCloud, but it's such a hog, requiring to be administered too often, for my taste, while Baikal 'just works', almost being invisible. :smile:

> If you are that kind of guy, may I also suggest password-store for your passwords? There are several packages to integrate password store with Emacs, Firefox and Android.

If you have something to recommend?

Otherwise, I use KeePassX...

> I'm using khard (to edit my contacts mostly) but not khal.

Well, now, after switching to Emacs/orgmode I also do not have need to use khal -- orgmode+org-caldav-sync do everything. :wink:

> I wrote all of the code to be able to use multiple repositories but never did that (as I only have one). 

:smile:

> What use case do you have? 

I _could_ manage to work with just one repo, but, it general, although I share lot of contacts with my wife's addresbook, still we keep different contacts as well.

> Would you prefer that vdirel shows all contacts from both repositories as if they came from the same? 

Would that be simpler for you? What about duplicate entries present in both repos?

> Or would you prefer to choose which repository is currently active and make all commands use that?

That would be convenient, indeed.

> Or would you prefer that each command first asks you which repository to fetch contacts from?

This is also not bad, but, I must admit, the whole concept of having proper app (khard) to easily add/edit contacts as well as to sync them with my phone and have them available within Emacs/Gnus is so nice, that I'm leaving it up to you what is the most simple to implement.

Maybe, ability to switch the currently active repo does provide more streamlined workflow instead of interrupting it by asking each time which repo to use?

Btw, just curious, did you ever use BBDB? It could be a great thing, but, somehow, I never managed to wrap my head around it, although, I confess, did not try hard enough. ::smile:

p.s. Still thinking whether to choose Pharo or Racket for writing desktop GUI app... :disappointed:

**Comment by DamienCassou** [comment]
> If you have something to recommend?
- http://passwordstore.org/
- https://github.com/DamienCassou/auth-password-store

> ability to switch the currently active repo does provide more streamlined workflow

ok, I can try

> did you ever use BBDB

no

**Comment by gour** [comment]
> I'm using khard (to edit my contacts mostly) but not khal.

How do you sync your calendars? I've problem with org-caldav-sync (see this [issue](https://github.com/dengste/org-caldav/issues/51)).

**Comment by DamienCassou** [comment]
> How do you sync your calendars? I've problem with org-caldav-sync (see this issue).

I just have one calendar.

**Comment by DamienCassou** [comment]
What do you think about the code in #3? You just have to fill `vdirel-repositories` with a list of your repository paths, and call `vdirel-switch-repository` to change the current one.

**Comment by gour** [comment]
Hello,

> You just have to fill vdirel-repositories with a list of your repository paths, 

vdirel-repositories has the following value:

```
vdirel-repositories is a variable defined in `vdirel.el'.
Its value is ("~/emacs/vdir/repo1" "~/emacs/vdir/repo2")
Original value was nil
```

and there are:

```
~/emacs/vdir/repo1/repo1.vcf
~/emacs/vdir/repo2/repo2.vcf
```

files with **different** contacts.

> and call vdirel-switch-repository to change the current one.

and after I did that, calling:

```
vdirel-helm-select-email
```

does not complete anything?

Do I miss something?

**Comment by DamienCassou** [comment]
Hmmm, that's surprising. This works fine for me. Make sure your 2 vcf files have at least 1 email address each. If this does not fix your problem, can you please try this sequence:
- `M-x vdirel-switch-repository`
- `M-: (setq vdirel--cache-contacts nil)`
- `M-x vdirel-helm-select-email`

If that does not work, can you please send me your 2 vcf files? Thanks

**Comment by gour** [comment]
> Hmmm, that's surprising.

Ahh...my mistake. :-(

I pointed my repository to the 'vdir' folders containing 'single-storage' instead of 'collection' folders...

So, it works nicely!
