### ISSUE TITLE
Test `vdirel--helm-email-candidates` failing

### ISSUE THREAD

**Issue by arjenpdevries** [DamienCassou/vdirel#26]
In response to pull request #24 I wrote a test, that however failed; I noticed however that it also fails on the current tree.

Here is how I run the tests:
```
emacs -batch -f package-initialize -L . -f buttercup-run-discover
```

The fix seems as easy as adding `nil` to the desired answers, but I am not 100% certain that this is the right solution. Could you please verify?

**Comment by DamienCassou** [comment]
Thank you for the report. This test started failing after a PR and with no configured CI, I didn't see the problem. In #27 I have configured a new CI so this won't happen again. Thanks again.

**Comment by arjenpdevries** [comment]
Great to setup CI. 
I may return here to learn how to do so for emacs code!

**Comment by DamienCassou** [comment]
"Arjen P. de Vries" ***@***.***> writes:
> I may return here to learn how to do so for emacs code! 

you may be interested in https://emacsconf.org/2019/talks/16/


-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
