### ISSUE TITLE
Make first use after startup of vdirel faster

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/vdirel#9]
On first access, vdirel is quite slow to  answer the list of contacts as it parses all vcard files. The next calls are very fast. The problem is that each time Emacs starts, the list has to be recomputed and the user has to wait.

Two solutions we can combine:
- store the data structure on the disk so that Emacs can use it at each first call
- propose a way to compute the data structure while Emacs is idle

**Comment by DamienCassou** [comment]
I solved that with https://gitlab.petton.fr/DamienCassou/khardel.

**Comment by Thaodan** [comment]
> I solved that with https://gitlab.petton.fr/DamienCassou/khardel.

How? Does the package replace this package?

**Comment by DamienCassou** [comment]
I indeed replaced vdirel with khardel in my configuration. I haven't used vdirel for years.
